### ISSUE TITLE
Authoring Tool: When creating a branch based on Choice Chosen, the step drop down should default to the current step

### ISSUE THREAD

**Issue by geoffreykwan** [WISE-Community/WISE#1007]
### Description

After selecting "Choice Chosen" in the drop down when creating a branch, it should automatically select the current step. If there is only one Multiple Choice component in the step, the component should automatically select that component.

### Steps to Reproduce

1. Open the authoring for a step
2. Go to the Advanced view
3. Click on "Create Branch"
4. Enter the number of branch paths e.g. 2
5. For the "How to choose among paths" select "Choice Chosen"
6. See that the "Choose Step" and "Choose Component" drop downs are not set to anything.

**Expected behavior:** The "Choose Step" and "Choose Component" drop downs should automatically be set when possible.

**Actual behavior:** The "Choose Step" and "Choose Component" are not set to anything.

**Comment by hirokiterashima** [comment]
Will keep this in mind when we rewrite the tool in Angular.
