### ISSUE TITLE
Redesign VLE step navigation to match CM (prev/next arrows surrounding the step drop-down)

### ISSUE THREAD

**Issue by breity** [WISE-Community/WISE#1024]
### Description
Classroom Monitor has a redesigned step navigation bar with previous and next arrows surrounding the step drop-down on the left-hand side of the toolbar. We should redesign the VLE to match.

![capture](https://user-images.githubusercontent.com/297450/33460026-2beecdb8-d5e1-11e7-8081-1b49582c0f61.PNG)

**Operating System:**
All

**Browser:**
All

**Comment by hirokiterashima** [comment]
Already done!
