### ISSUE TITLE
Extract common function in ProjectService.turnOn/OffSaveButtonInComponents

### ISSUE THREAD

**Issue by hirokiterashima** [WISE-Community/WISE#1031]
### Description

In ProjectService,
```turnOnSaveButtonInComponents(nodeId)```
and 
```turnOffSaveButtonInComponents(nodeId)```

are very similar in structure. Factor out the common block to avoid duplication.

**Comment by geoffreykwan** [comment]
These functions were refactored in this commit https://github.com/WISE-Community/WISE/commit/409c67fd8872abaf350bde1edbe80dd07c284b01
