### ISSUE TITLE
Authoring Tool: Show multiple levels of branching with more letters and indentation

### ISSUE THREAD

**Issue by geoffreykwan** [WISE-Community/WISE#1048]
### Description

Right now if a project contains a branch and one of those branch paths contains another branch, the Authoring Tool project view won't show any indication of this multiple level of branching.

Multiple levels of branching should display step titles with an additional letter for each branch level. For example
>                               (1.1)
>                             /       \
>                      (1.2 A)         (1.2 B)
>                      /              /       \
>               (1.3 A)       (1.3 BA)         (1.3 BB)

In the project view, each level of branching should also receive an additional level of indenting. Right now steps in a branch path receive one level of indenting no matter how many levels of branching they are in.

**Comment by hirokiterashima** [comment]
We will address this when we rewrite AT in Angular.
