### ISSUE TITLE
Site: Implement the server backend code for handling a student registering for a run

### ISSUE THREAD

**Issue by geoffreykwan** [WISE-Community/WISE#1058]
### Description

We need to handle a request that receives a run code and returns a list of period ids. We also need to handle a request that receives a run code, period id and student id and then registers a student with that run and then returns information about the run so it can be displayed in the student run list. This code might go in StudentAPIController.java.

**Comment by hirokiterashima** [comment]
This has been implemented in StudentAPIController as createStudentAccount(), addStudentToRun() and getRunInfo() methods.
