### ISSUE TITLE
IE7&8: show flagged work grays out screen and nothing happens

### ISSUE THREAD

**Issue by geoffreykwan** [WISE-Community/WISE#111]
<b>What steps will reproduce the problem?</b>
1. log in as student, launch VLE.
2. click on "Show Flagged Work".

<b>What is the expected output? What do you see instead?</b>
grays out with stripes, nothing happens after that. nothing is interact-able because the gray panel is modal.

should see 'no flagged item for this step' panel.

there is a warning in IE browser:
Invalid argument.
jquery-1.4.2.min.js Line 116
code:0
uri: http://..../vlewrapper/vle/jquery/js/jquery-1.4.2.min.js

Google Code Info:
Issue #: 110
Author: honchikun
Created On: 2011-01-13T00:24:16.000Z
Closed On:

**Comment by breity** [comment]
N/A - not supporting <ie9
