### ISSUE TITLE
Internet connection error message displays when student tries to upload a file that is too large

### ISSUE THREAD

**Issue by breity** [WISE-Community/WISE#1124]
### Description
If students try to upload a file that is too large or would exceed the allowed file storage, a pop-up message indicating that they've run out of storage space correctly displays. They then get a message at the bottom of the screen: "Error: Data is not being saved! Check your internet connection." This is due to the fact that the HttpInterceptor looks for server errors 500, 503, 504, and -1 and treats all of these as a disconnection. We should make the error more specific and only show the message when an actual server disconnection occurs, if possible.

### Steps to Reproduce

1. As a student, try to upload an image to a post in a discussion component.

**Comment by geoffreykwan** [comment]
We will address this when we rewrite CM in Angular.
