### ISSUE TITLE
New site: update header links on login

### ISSUE THREAD

**Issue by breity** [WISE-Community/WISE#1130]
### Description

On the new site, the register/sign in links still show up in the header and the account menu does not appear unless the page is reloaded after logging in.

### Steps to Reproduce

1. Go to /site
2. Click "Sign In"
3. Log in with WISE account

**Expected behavior:**

The header should show the account menu icon (avatar) and the Register and Sign In links should disappear.

**Actual behavior:**

Register and Sign In are still visible and account menu doesn't appear in the header until you refresh the page.

**Comment by hirokiterashima** [comment]
This was resolved in #1141.
