### ISSUE TITLE
Concept Map: Nodes without image is not moveable

### ISSUE THREAD

**Issue by hirokiterashima** [WISE-Community/WISE#1144]
### Description

Concept Map node with just label text and no image will not allow the node to be moved onto canvas.

**Operating System:** Mac OSX

**Browser:** Chrome

### Steps to Reproduce

1. Create a Concept Map component in the AT
2. Add a new node
3. Set the label text but don't set the image file
4. Preview the component

**Expected behavior:** I should be able to move the new node onto canvas

**Actual behavior:** The new node is not moveable. 

### Additional Information
The mouse pointer changes when hovering over the icon. There are no errors in the console.

**Comment by geoffreykwan** [comment]
We will address this when we rewrite CM in Angular.
