### ISSUE TITLE
Refactor ProjectService.es6: reduce loading time for projects with lots of branching

### ISSUE THREAD

**Issue by hirokiterashima** [WISE-Community/WISE#1154]
Goal: “for project with X branches and Y nodes, the VLE should load in under Z seconds”
Measurable goal: “given input X, it currently takes Y seconds. It should complete in Z seconds.”

**Improve efficiency of ProjectService.getBranches().**
**Improve efficiency of ProjectService.calculateNodeNumbers().**

**Comment by geoffreykwan** [comment]
We will address this when we rewrite CM in Angular.
