### ISSUE TITLE
Grading Tool: Online status dot does not activate

### ISSUE THREAD

**Issue by hirokiterashima** [WISE-Community/WISE#1160]
### Description

In the grading tool, when the student logs in, the online dot does not activate.

**Operating System:** Mac OS

**Browser:** Chrome

### Steps to Reproduce

1. Open grading tool as a teacher of the run and go to Grade by Team view.
2. Open run as student in another window.

**Expected behavior:** 
The "Online" dot should highlight for the student.

**Actual behavior:** 
The "Online" dot remains inactive.

![screen shot 2018-04-20 at 10 59 07 am](https://user-images.githubusercontent.com/119416/39066672-b91c40e0-448a-11e8-8996-350b4d003b10.png)

**Comment by geoffreykwan** [comment]
We will address this when we rewrite CM in Angular.
