### ISSUE TITLE
Refactor ProjectService.updateTransitionsForExtractingGroup()

### ISSUE THREAD

**Issue by hirokiterashima** [WISE-Community/WISE#1193]
### Description

Functions listed below were identified by IntelliJ code inspector as being overly nested. Get all of the functions to be depth <=5.

### Functions to refactor
```
function 'updateTransitionsForExtractingGroup' is overly nested (maximum nesting depth = 8)
```

**Comment by geoffreykwan** [comment]
We will address this when we rewrite in Angular.
