### ISSUE TITLE
Refactor ProjectService.updateChildrenTransitionsIntoGroupWeAreMoving()

### ISSUE THREAD

**Issue by hirokiterashima** [WISE-Community/WISE#1195]
### Description

Functions listed below were identified by IntelliJ code inspector as being overly nested. Get all of the functions to be depth <=5.

### Functions to refactor
```
function 'updateChildrenTransitionsIntoGroupWeAreMoving' is overly nested (maximum nesting depth = 9)
```

**Comment by geoffreykwan** [comment]
We will address this when we rewrite in Angular.
