### ISSUE TITLE
Teacher scores and comments do not appear for audioOscillator component

### ISSUE THREAD

**Issue by hirokiterashima** [WISE-Community/WISE#1211]
### Description

Teacher comments and scores are not showing up in the students' view for audio oscillator component.

### Steps to Reproduce

1. Log in as teacher, give score/comment to student on an audio oscillator component
2. Log in as student, go to audio oscillator component

**Expected behavior:** score/comment from step 1 should appear for student.

**Actual behavior:** score/comment from step 1 does not appear for student.

**Comment by geoffreykwan** [comment]
We will address this when we rewrite in Angular.
