### ISSUE TITLE
New ProjectLibrary search bug after hitting reset

### ISSUE THREAD

**Issue by hirokiterashima** [WISE-Community/WISE#1220]
### Description

Keyword search no longer works after clicking on 'reset'

### Steps to Reproduce

1. Type keyword in search box and hit enter
2. Click on reset
3. Type same keyword in search box and hit enter

**Expected behavior:** 
You should see the same result in 1 and 3.

**Actual behavior:**
In 3, there is no indication that the search took place. It looks like search didn't work.

### Additional Information

If you click on the "x" in step 2 instead of hitting 'reset', everything works.

**Comment by breity** [comment]
Done in #1221.
