### ISSUE TITLE
Draw: cannot add initial drawing to notebook 

### ISSUE THREAD

**Issue by hirokiterashima** [WISE-Community/WISE#1251]
### Description

A student cannot add the initial drawing as a note to their notebook. They must make a change to the initial drawing before it can be made into a note.

There are two ways that we can approach this:
1. Disable the "Add to Notebook" button until there is work that can be saved.
2. Allow students to add initial, unchanged drawing to their notebook.

**Operating System:** Mac OS

**Browser:** Chrome

### Steps to Reproduce

1. Open a step with the drawing component
2. Without making any changes, click on the "add to notebook" button.

**Expected behavior:** Nothing happens. No feedback is given.

**Actual behavior:** See the two possible solutions in the Description section.

**Comment by geoffreykwan** [comment]
We will address this when we rewrite in Angular.
