### ISSUE TITLE
Notebook: hitting escape to dismiss the notebook also removes notebook button

### ISSUE THREAD

**Issue by hirokiterashima** [WISE-Community/WISE#1257]
### Description

Instead of hitting the "x" at the top right to dismiss the notebook, if you hit "esc", it will hide the notebook panel. This will also hide the notebook icon in the bottom right, and only show the "add note" button in its place. 

**Operating System:** Mac OSX

**Browser:** Chrome

### Steps to Reproduce

1. Open notebook via the "notebook" button in the bottom-right corner
2. Hit "esc". This will hide the notebook

**Expected behavior:** the "notebook" button in the bottom-right corner should be visible.

**Actual behavior:**  the "notebook" button in the bottom-right corner is hidden, and in its place, you see the "add note" button.

Additional Note:
Should we just disable the "esc" to hide option?

**Comment by geoffreykwan** [comment]
We will address this when we rewrite in Angular.
