### ISSUE TITLE
Hide Notebook tabs when only private (or public) notes are enabled

### ISSUE THREAD

**Issue by breity** [WISE-Community/WISE#1266]
When public notes are disabled for a project, the tabs at the top of the Notebook sidebar in the VLE still show up. There is only one tab ("Personal"). The tabs should be hidden if only one type of note (public or private) is enabled.

![notebook-single-tab](https://user-images.githubusercontent.com/297450/41392253-7ae6a212-6f54-11e8-8e17-5c619a99cd46.PNG)

**Comment by geoffreykwan** [comment]
We will address this when we rewrite in Angular.
