### ISSUE TITLE
Include option to add "alt" attribute to images in the authoring tool

### ISSUE THREAD

**Issue by breity** [WISE-Community/WISE#1267]
All images need to have an "alt" attribute to follow HTML accessibility guidelines. We should allow (or require) authors to specify alternate text when they upload an image in the authoring tool.

The alternate text should automatically be inserted into the step HTML content when an author adds it. We should also allow authors to overwrite the default alternate text when inserting an image into component content (using the rich text editor, for example).

**Comment by geoffreykwan** [comment]
We will address this when we rewrite in Angular.
