### ISSUE TITLE
GT: Enlarge SVGDraw bug

### ISSUE THREAD

**Issue by geoffreykwan** [WISE-Community/WISE#129]
<b>What steps will reproduce the problem?</b>
1. open grade-by-step for a svgdraw step
2. click on enlarge for work without snapshot(?)

<b>What is the expected output? What do you see instead?</b>
svgdraw tool loads with blank canvas.

should load student's last drawing.

Google Code Info:
Issue #: 128
Author: honchikun
Created On: 2011-02-02T01:36:34.000Z
Closed On:

**Comment by breity** [comment]
Working.
