### ISSUE TITLE
Updating maxScore refreshes the entire step view

### ISSUE THREAD

**Issue by hirokiterashima** [WISE-Community/WISE#1296]
### Description

It looks like updating the max score via the grade-by-step view refreshes the entire step view.

**Operating System:** Mac OSX

**Browser:** Chrome

### Steps to Reproduce

1. Open any component in grade-by-step in classroom monitor
2. Edit the max score

**Expected behavior:** The max score should be updated in place. Nothing else should happen.

**Actual behavior:** 
The max score is updated, but the entire view indow seems to refresh and any expanded workgroups/steps are collapsed, so it's surprising to the user.

### Additional Information
Entering score also seems to exhibit the same behavior of the component refreshing.

**Comment by geoffreykwan** [comment]
We will address this when we rewrite in Angular.
