### ISSUE TITLE
Provide UI for authors to specify step and activity icons and colors

### ISSUE THREAD

**Issue by breity** [WISE-Community/WISE#1297]
Right now, authors need to edit step and activity json to specify the item's icon and color. We should add a simple UI for this in the authoring tool.

So for each activity and step, we could have a color picker with a set of colors for them to choose from. Same for icons - a picker that lets them browse the Material Design icons (and maybe others).

When authors choose a color for an activity, we should automatically set that color for all the steps within that activity. Authors could then override if they like.

**Comment by geoffreykwan** [comment]
We will address this when we rewrite in Angular.
