### ISSUE TITLE
AT: Insert After Arrow does not appear after deleting only component

### ISSUE THREAD

**Issue by hirokiterashima** [WISE-Community/WISE#1301]
### Description

The "insert after" arrow does not appear after removing the last component.

**Operating System:** Mac OSX

**Browser:** Chrome

### Steps to Reproduce

1. In the AT, open a step with one component.
2. Delete the component.
3. Add a new component.

**Expected behavior:**
The "insert after" arrow should appear to let me choose the location for the new component.

**Actual behavior:**
The arrow does not appear and I cannot add the new component to the step.

**Comment by geoffreykwan** [comment]
We will address this when we rewrite in Angular.
