### ISSUE TITLE
Don't allow teachers or students to see any student or workgroup IDs

### ISSUE THREAD

**Issue by breity** [WISE-Community/WISE#1334]
To comply with new CPHS rules for future grants, we can't let teachers (or students) see any WISE IDs (studentId or workgroupId). This includes in the:

- VLE
- Classroom Monitor
- Portal (currently, teachers can see workgroup and student IDs in the Manage Students tool for a run)

We should create a run-specific ID for each workgroup. (For now, this could just be "Team #", an integer starting with 1. Later on, maybe students could choose an avatar of sort like an animal and we could use the animal name.)  This will  give students and teachers an easy way to refer to workgroups and also allow us to add a Team column to the new gradebook view that teachers can sort by.

**Comment by geoffreykwan** [comment]
We will address this when we rewrite in Angular.
