### ISSUE TITLE
Gradebook: Highlight Cells by Status

### ISSUE THREAD

**Issue by hirokiterashima** [WISE-Community/WISE#1366]
### Description

Add highlighting of step cells to the gradebook to indicate status (completed, not assigned). Completed should match color of the gradebook theme.

![image](https://user-images.githubusercontent.com/119416/43428836-2cb39434-9415-11e8-827e-8a9a8f32f961.png)

**Comment by geoffreykwan** [comment]
We will address this when we rewrite in Angular.
