### ISSUE TITLE
Gradebook: Add Click Actions

### ISSUE THREAD

**Issue by hirokiterashima** [WISE-Community/WISE#1367]
### Description

Actions are:
- click on username to open grade-by-team for that student's workgroup
- click on step numbering to open grade-by-step view
- click on step status cell (containing score and/or color/disabled) to open up the grade-by-step view and scroll to that team's work. All other teams would be collapsed in this view.

![image](https://user-images.githubusercontent.com/119416/43428932-a28566ba-9415-11e8-9f69-c71f60c7e589.png)

[Description of the issue]

**Operating System:** [your OS]

**Browser:** [your browser information]

### Steps to Reproduce

1. [First Step]
2. [Second Step]
3. [and so on...]

**Expected behavior:** [What you expect to happen]

**Actual behavior:** [What actually happens]

### Additional Information

[Any additional information, configuration or data that might be necessary to reproduce the issue.]

(If this is a feature request, tag this issue with "Feature Request")

**Comment by geoffreykwan** [comment]
We will address this when we rewrite in Angular.
