### ISSUE TITLE
Allow students to register with Google Account

### ISSUE THREAD

**Issue by hirokiterashima** [WISE-Community/WISE#1400]
Allow new student to sign in with their Google account.

Step:

Go to create new student page.
Click on the "Sign Up with Google Authentication" button.
This will ask the user to log in to their Google Account if they haven't already.
Once authentication with Google is completed, they will be asked to agree to WISE's terms of use and fill out some extra fields like birthday, birthmonth.
Click submit, and a new account will be created for them. They can use their Google account to log in from then on.

![image](https://user-images.githubusercontent.com/119416/44493286-444d1e80-a61c-11e8-9548-02df2c7b52a0.png)

![image](https://user-images.githubusercontent.com/119416/44493288-46af7880-a61c-11e8-8715-d65f1b81be06.png)

**Comment by breity** [comment]
Closed by #1403.
