### ISSUE TITLE
Site: Navigating to /join/teacher or /join/student breaks app

### ISSUE THREAD

**Issue by breity** [WISE-Community/WISE#1411]
### Description

Navigating with url directly to /join/teacher and /join/student is broken.

**Expected behavior:**
Users should be able to go directly to the Create Teacher Account and Create Student Account pages.

**Actual behavior:**
Application breaks, results in:
`ERROR TypeError: Cannot read property 'googleClientId' of null
    at ConfigService.push../src/app/services/config.service.ts.ConfigService.getGoogleClientId (config.service.ts:70)`

**Comment by vkorir** [comment]
@geoffreykwan seems like this is no longer the case. i am correctly navigated to the student/teacher registration page when i enter the urls.

**Comment by vkorir** [comment]
fixed in another issue
