### ISSUE TITLE
Implement "WISE Tested" library tab

### ISSUE THREAD

**Issue by geoffreykwan** [WISE-Community/WISE#1422]
The "WISE Tested" tab will contain the projects that our researchers have created and fine tuned. 

Teachers can
- filter projects
- create a run
- copy a project
- add a project to favorites

Make a WISE Tested component that is similar to or extends the existing home page library component.

![image](https://user-images.githubusercontent.com/1036509/44816058-26992f80-abaf-11e8-9f9d-4f901ebc8ad9.png)

**Comment by breity** [comment]
Closed by #1426.
