### ISSUE TITLE
Automatically add edited run projects to my projects

### ISSUE THREAD

**Issue by breity** [WISE-Community/WISE#1451]
Since creating a run will only be possible from the library, we should add any run project that has been edited to a user's My Projects list. This way, they can create a new run with the edited project (and eventually add to favorites, group with other projects, etc).

We should also add an explanation (via info icon or something) of why the project is there/where it came from.

**Comment by geoffreykwan** [comment]
I'm wondering if we should use the favorites functionality to handle this situation when teachers want a run project to show up in their personal library. Favorites would give them more control over what shows up in their personal library.

If they just edited a run project to fix a typo, they might not want that project to automatically show up in their personal library. They also wouldn't have a way to remove it from their personal library either.

**Comment by geoffreykwan** [comment]
We will address this when we rewrite in Angular.
