### ISSUE TITLE
Show parent project ID in the library project details menu

### ISSUE THREAD

**Issue by breity** [WISE-Community/WISE#1466]
If project is a copy of another project, we should show the parent project's ID in the project details dialog dropdown menu. Putting at the top of the menu allows for anyone to get the info and doesn't add clutter to dialog.

**Comment by hirokiterashima** [comment]
This would be similar to how we display Run ID at the top of the run details menu. (reference run-menu.component)

![screen shot 2018-10-03 at 8 53 52 am](https://user-images.githubusercontent.com/119416/46422821-f8e16200-c6e9-11e8-9eab-e3f5201733eb.png)
