### ISSUE TITLE
Auto-save seems bugged again for OR/Questionnaire

### ISSUE THREAD

**Issue by geoffreykwan** [WISE-Community/WISE#150]
From elissa

Students are reporting to me that auto-save is not working, and they are reporting this to me enough that I don't think it's a fluke. Seems to happen for both open response and questionnaire. For questionnaire it seems sometimes the page goes blank (i.e. not going to the next/previous page)--not sure if students are again hitting some weird key combination--and that does not allow auto-save to kick in. It is not an inet issue b/c Martinez's wireless is very stable.

http://wise4.berkeley.edu/webapp/vle/preview.html?projectId=696

The questionnaires in activity 3 - no one in particular seemed prevalent, but many students would call me over during this time.

For OR, 6.5 - one specific instance was this one. It displays previous work.

Google Code Info:
Issue #: 149
Author: honchikun
Created On: 2011-03-15T17:44:34.000Z
Closed On:

**Comment by hirokiterashima** [comment]
No longer a recurring issue.
