### ISSUE TITLE
Running library.* tests results in error but not when running all tests

### ISSUE THREAD

**Issue by hirokiterashima** [WISE-Community/WISE#1528]
### Description
When running all the tests, the tests pass, but when you limit the test to just files that have filename library.*.spec.ts, one test fails and we see an error.

**Operating System:** Mac OSX, Windows

**Browser:** N/A

### Steps to Reproduce

In test.ts, change 
```
const context = require.context('./', true, /\.spec\.ts$/);
```
to
```
const context = require.context('./', true, /library.*\.spec\.ts$/);
```

**Expected behavior:** 
All tests should pass

**Actual behavior:** 
You get 1 failed tests and an error in the console:
```
Chrome 69.0.3497 (Mac OS X 10.13.6) PersonalLibraryComponent should create FAILED
[1] 	[object ErrorEvent] thrown
[1] Chrome 69.0.3497 (Mac OS X 10.13.6): Executed 19 of 22 (1 FAILED) (0 secs / 0.776 secs)
[1] Chrome 69.0.3497 (Mac OS X 10.13.6) PersonalLibraryComponent should create FAILED
    Chrome 69.0.3497 (Mac OS X 10.13.6): Executed 22 of 22 (1 FAILED) (0.993 secs / 0.97 secs)
[1] TOTAL: 1 FAILED, 21 SUCCESS
```

### Additional Information

We think this may be because the unit tests are not independent of each other when it should be. Running all the tests pass because this problem is somehow covered up.

**Comment by geoffreykwan** [comment]
All library tests now pass when only running library tests.
