### ISSUE TITLE
Notebook Report grading does not save

### ISSUE THREAD

**Issue by geoffreykwan** [WISE-Community/WISE#1617]
### Steps to Reproduce

1. Have a student write something in their report and save it.
2. As the teacher, go to the Notebook/Report view in the Classroom Monitor.
3. Open the report for the student and give them a comment and score.
4. Refresh the Classroom Monitor to see if the comment and score saved.

**Expected behavior:**
The comment and score should save.

**Actual behavior:** 
The comment and score does not save.

**Comment by hirokiterashima** [comment]
This was fixed while we worked on the teacher notebook.
