### ISSUE TITLE
Can't create news items on the new site

### ISSUE THREAD

**Issue by breity** [WISE-Community/WISE#1638]
Trying to create a news item from the admin tools results in a 404 Not Found error.

To reproduce:
- Log in to new site as an admin and go to `/admin/news/managenewsitems.html`.
- Click "Add News Item".

What should happen:
- Pop-dialog opens and loads the add news item form in an iframe.

What actually happens:
- Pop-up dialog opens and shows 404 Not Found error.

**Comment by hirokiterashima** [comment]
Looks like a pathing issue. Should be simple to fix. I'll look into it.
