### ISSUE TITLE
Sign in is broken after session timeout or if user is already logged in

### ISSUE THREAD

**Issue by breity** [WISE-Community/WISE#1652]
### Description

If a user is logged out due to inactivity and tries to navigate somewhere, user will be redirected to the login page. After trying to sign in, a snackbar message appears: "An error occurred. Please check your connection and try again." These js errors occur (when logging in as an admin, for example):

`login:1 Mixed Content: The page at 'https://wise.berkeley.edu/login' was loaded over HTTPS, but requested an insecure XMLHttpRequest endpoint 'http://wise.berkeley.edu/admin'. This request has been blocked; the content must be served over HTTPS.`

`main.bf5544332ffa30003d58.js:1 Backend returned code 0, body was: [object ProgressEvent]
(anonymous) @ main.bf5544332ffa30003d58.js:1`

`main.bf5544332ffa30003d58.js:1 ERROR `

### Steps to Reproduce

1. Log in to site.
2. (a) Let your login timeout due to inactivity and try to navigate somewhere. You will be redirected to `/login`. **-OR-** (b) Navigate directly to `/login` while still signed in.
3. Try to sign in again using any valid account credentials.

**Expected behavior:**

User should be redirected to the student or teacher home page.

**Actual behavior:**

User stays on login page and sees error message.

**Comment by hirokiterashima** [comment]
This was fixed in a previous commit
