### ISSUE TITLE
Hebrew project names do not show up properly in the library in the new site

### ISSUE THREAD

**Issue by geoffreykwan** [WISE-Community/WISE#1663]
The server side seems to be retrieving the Hebrew text properly. Perhaps it's the client response where the Hebrew is lost?

1. Log in as a teacher
2. Go to the project library (make sure you have a project that has a Hebrew name)
3. The project tile will look like the screenshot below

![unnamed](https://user-images.githubusercontent.com/1036509/49042969-a11a2100-f197-11e8-9760-d1021aaad0dd.png)

**Comment by hirokiterashima** [comment]
It looks like the server is returning ???. If you copy the request link and paste on a new tab, you can see that the response JSON contains the ???.
