### ISSUE TITLE
Display warning when setting up a WISE4 unit run

### ISSUE THREAD

**Issue by hirokiterashima** [WISE-Community/WISE#1668]
### Description

Show a warning dialog when the teacher clicks on the "Use with Class" button for a WISE4 project. 

The warning dialog should say:
`<p class="mat-subheading-2 accent-1">{{ project.metadata.title }} <span class="mat-caption" i18n>(Unit ID: {{ project.id }})</span></p><p style="mat-body-2">Warning: this is a legacy unit in a version of WISE that is many years old.</p><p>We recommend finding a newer version of this unit in the library, as support for classroom implementations of legacy units will be phased out over the coming year. If you cannot find a newer version, contact us if you're interested in upgrading the unit. Thanks!</p>`

The buttons on the warning dialog should be:
"Proceed Anyway" => display the run set up dialog
"Cancel" => close the warning dialog

**Comment by hirokiterashima** [comment]
@breity can you please review the description?

**Comment by geoffreykwan** [comment]
Completed in #1768
