### ISSUE TITLE
Can add myself to team

### ISSUE THREAD

**Issue by hirokiterashima** [WISE-Community/WISE#1699]
### Description

In the team sign in form. I can add myself as a team member. It adds my id multiple times in the student_attendance table. But next time I open the team sign in form they do not show up (which is good).

### Steps to Reproduce

1. In the team sign in form for a multiple-member run, add currently logged in user as user 2.

**Expected behavior:**
This should not be allowed. We should show a message, like "You cannot add yourself."

**Actual behavior:**
This is allowed.

**Comment by vkorir** [comment]
i think i worked on an issue that resolves this. refer to #1771

**Comment by hirokiterashima** [comment]
Yes this is a duplicate.
