### ISSUE TITLE
Students can still work on a run that has been ended by a teacher

### ISSUE THREAD

**Issue by geoffreykwan** [WISE-Community/WISE#1766]
1. Do some work on a run as a student.
2. Have the teacher end the run.
3. Have the student launch the run.
4. The student can still modify old work and add new work when they shouldn't be able to.

Perhaps we should prevent new student work on an ended run on the client side as well as the server side.

**Comment by hirokiterashima** [comment]
@geoffreykwan has this been resolved in #1912 ?

**Comment by geoffreykwan** [comment]
@hirokiterashima yea it's been resolved, I'll close this
