### ISSUE TITLE
Grading Change Project Run button: Ajax request->drop down selection of gradable runs

### ISSUE THREAD

**Issue by geoffreykwan** [WISE-Community/WISE#185]
The "Change Project Run" button currently takes the user to another page where they select another run to grade.

Change this so they can choose the run from the grading tool.

Ex: when the button is clicked, do an Ajax request to retrieve runs that the user can grade. Then show them in a drop-down select menu, and clicking on them will open the grading tool for that selected run.

Google Code Info:
Issue #: 184
Author: honchikun
Created On: 2011-04-12T18:16:33.000Z
Closed On:

**Comment by breity** [comment]
N/A
