### ISSUE TITLE
Bug branching on MC choosing path on autosave

### ISSUE THREAD

**Issue by hirokiterashima** [WISE-Community/WISE#1860]
### Description

On a branching activity based on choice chosen on a MC component, the branch path is chosen on auto-save. If the student changes a different item, the branch path remains fixed.

### Steps to Reproduce
1. Import this project:
[129.zip](https://github.com/WISE-Community/WISE/files/2994417/129.zip)

2. Preview the project.
3. On step 1, choose A, and don't do anything for a while so the auto-save happens.
4. Change choice to choice B, hit save, and go to the next step

**Expected behavior:**
You should go to path B

**Actual behavior:**
You go to path A

**Comment by geoffreykwan** [comment]
We will address this when we rewrite in Angular.
