### ISSUE TITLE
Graph Component: Allow multiple graphs to be imported into a single graph

### ISSUE THREAD

**Issue by geoffreykwan** [WISE-Community/WISE#1883]
### Steps to Reproduce

1. Author a step with Graph 1
2. Author a step with Graph 2
3. Author a step (Graph 3) that will import the work from Graph 1 and Graph 2
4. Preview the project and add points to Graph 1 and Graph 2
5. Go to Graph 3

**Expected behavior:**

Graph 1 and Graph 2 should be imported into Graph 3.

**Actual behavior:**

Only one of the graphs is imported into Graph 3.

**Comment by hirokiterashima** [comment]
closed by #1908
