### ISSUE TITLE
student can not edit graph

### ISSUE THREAD

**Issue by house1994** [WISE-Community/WISE#1902]
### Description

one student can not edit the graph, but other in the same class can edit...
**Operating System:windows
<img width="811" alt="WechatIMG9944" src="https://user-images.githubusercontent.com/33342166/56938289-993e1e80-6b33-11e9-824f-dd35ce9052ef.png">

**Browser:chrome

### Steps to Reproduce

1. [First Step]
2. [Second Step]
3. [and so on...]

**Expected behavior:** [What you expect to happen]

**Actual behavior:** [What actually happens]

### Additional Information

[Any additional information, configuration or data that might be necessary to reproduce the issue.]

(If this is a feature request, tag this issue with "Feature Request")

**Comment by hirokiterashima** [comment]
@house1994 What's the difference between students who can edit and who can't? Do you notice any errors in the javascript console?

**Comment by geoffreykwan** [comment]
This might be a problem with how the teacher authored the component. User did not follow up. Please open an issue if this is still a problem.
