### ISSUE TITLE
Design new site admin page for teacher and student search

### ISSUE THREAD

**Issue by geoffreykwan** [WISE-Community/WISE#1941]
Design a wireframe for the teacher and student admin search pages.

This could either be
- a single page where admins can search for teachers or students
- two separate pages, one to search for teachers and one to search for students

The search pages could possibly utilize a form with input fields for
- first name
- last name
- username
- email (if teacher)
- etc

Also design the way the search results will be displayed.

**Comment by breity** [comment]
https://balsamiq.cloud/s8brvqj/p9j1not/r45E6
