### ISSUE TITLE
Implement class aggregate data view in the VLE for Multiple Choice

### ISSUE THREAD

**Issue by geoffreykwan** [WISE-Community/WISE#1976]
### Description

The graph component should be able to import work from the class period for Multiple Choice components and display a graph of the aggregate data
- Show how many workgroups chose each choice (show the percentage and count)
- If there is correctness, allow the option to show the graph of correct vs incorrect
- Allow choosing the display of a bar graph or pie graph

**Comment by breity** [comment]
Replaced by #2005.
