### ISSUE TITLE
Portal: Set up Run, part 2: check all open runs to archive by default

### ISSUE THREAD

**Issue by geoffreykwan** [WISE-Community/WISE#198]
By default, all open runs should be archived when a new run is being set up.

In setupruns part 2, where user specifies which open run(s) to archive, check all open run(s) by default.

Google Code Info:
Issue #: 197
Author: honchikun
Created On: 2011-04-28T20:06:11.000Z
Closed On:

**Comment by hirokiterashima** [comment]
This should not be the default behavior
