### ISSUE TITLE
Saving a project in the Authoring Tool throws NullPointerException if the project database row has NULL metadata field

### ISSUE THREAD

**Issue by geoffreykwan** [WISE-Community/WISE#1987]
### Description

1. In the database, find a project and set the metadata field to NULL
2. Log in as a teacher that owns that project
3. Open the project in the Authoring Tool
4. Make a change to the project and have it auto save
5. The exception below will be thrown on the server

```
java.lang.NullPointerException
	at org.wise.portal.presentation.web.controllers.author.project.WISE5AuthorProjectController.saveProject(WISE5AuthorProjectController.java:324)
```

**Comment by hirokiterashima** [comment]
All WISE5 projects must have a non-null metadata.
