### ISSUE TITLE
Convert Thermo flash model to video

### ISSUE THREAD

**Issue by hirokiterashima** [WISE-Community/WISE#2083]
### Description

1. Convert this flash model into video https://wise.berkeley.edu/project/29408#/vle/node29
   1. Remove the start/reset button. The students can use the video playback.
1. Update other library project(s) as needed.

**Comment by geoffreykwan** [comment]
This flash model has been converted to a video and updated in the library unit. You can preview it here
https://wise.berkeley.edu/preview/unit/31632/node29
