### ISSUE TITLE
Shared owners of run should be able to edit max score of run

### ISSUE THREAD

**Issue by geoffreykwan** [WISE-Community/WISE#213]
Currently only these people can edit the max point values:

- owner of run
- owner of project
- shared owner of project (with permissions to edit project)

Fix this so that shared owners of the run with permissions to grade will be able to change the max score.

Google Code Info:
Issue #: 212
Author: honchikun
Created On: 2011-05-10T18:58:09.000Z
Closed On:

**Comment by hirokiterashima** [comment]
@geoffreykwan can you test this out?
