### ISSUE TITLE
"Edit Content" link from run menu in teacher Class Schedule doesn't open the unit in the authoring tool.

### ISSUE THREAD

**Issue by breity** [WISE-Community/WISE#2139]
Clicking the "Edit Content" option in the run menu for run in the teacher Class Schedule opens the authoring tool but doesn't load the select unit. The link redirects to `/author`.

To reproduce:
1. Sign in as a teacher.
2. From the Class Schedule, open the run menu for a run in the list and select "Edit Content".
3. Click "Proceed" in the warning dialog.
4. Browser will load `http://localhost:8080/author#/project/[projectId]` and will redirect to `http://localhost:8080/author#!/`.

**Comment by hirokiterashima** [comment]
Did you run ```npm run build-dev-all```? This was fixed in AngularJS 1.5.11 -> 1.7.8 upgrade: https://github.com/WISE-Community/WISE/commit/c5eb9fd26b5a5d6277bd243e8878639aef07b9d0#diff-b81fceb8411e4143e61bc7adb78f6008L140

**Comment by breity** [comment]
@hirokiterashima Yep, looks like the issue has been resolved on develop now. Closing.
