### ISSUE TITLE
In admin page, student Info popup shows error page

### ISSUE THREAD

**Issue by geoffreykwan** [WISE-Community/WISE#2177]
### Description

1. Log in as an admin
1. Go to the Admin page
1. Find a student
1. Click the "Info" link for the student
1. The popup will show an error

```
Whitelabel Error Page
This application has no explicit mapping for /error, so you are seeing this as a fallback.

Thu Jan 09 08:28:56 PST 2020
There was an unexpected error (type=Forbidden, status=403).
Forbidden
```

**Comment by geoffreykwan** [comment]
This was fixed in https://github.com/WISE-Community/WISE/commit/e423548d79376bab0f071df38519e97c4abd868b

**Comment by hirokiterashima** [comment]
This was fixed by Eric in his latest PR. It was related to teacher use not
having permission to access the student path in WebSecurityConfig.java
