### ISSUE TITLE
Implement authoring structures

### ISSUE THREAD

**Issue by geoffreykwan** [WISE-Community/WISE#2203]
### Description

Add a feature in the Authoring Tool that allows teachers to insert an activity that contains pre-populated steps based on the activity structure they choose.

 - Add button maybe to the right of “Create New Step” button “Create Activity Structure”
 - The button will display an inline area to select the template type
 - Inline area will display the options for the template structures. Start with 3 (4th and 5th won’t be included for now).
Each option should contain a description of the template and a “Choose” button.
Jigsaw
Guidance Choice
Self Directed Investigation
Peer Review and Revision
KI Cycle using an OER
 - Clicking on the “Choose” button for an option will hide all the options and then display the form for the selected option.
 - The form for each option may be different.
 - Authors will fill out the form and then click submit.
 - Then we show the “Insert Activity” mode to let them choose where to insert the activity template.
 - If they click Cancel while in the “Insert Activity” mode, cancel the entire flow
 - If they click Cancel on the form, cancel the entire flow
 - Show breadcrumbs for the different stages. (In future, we could use a stepper or something like it: https://material.angular.io/components/stepper/overview)
Choose Template
Fill Out Form
Select Location
Use “Previous” and “Next” buttons to go back and forth between stages.
	Next button should be disabled until they select the type 

Specifications:
https://docs.google.com/document/d/1tPAECMEu15xh8N9ZLGe0dZ_QMNqWvva9e3mg_1DHxkw/edit.

Content for structures: https://wise.berkeley.edu/project/30841#!/project/30841/

**Comment by hirokiterashima** [comment]
Closed by #2228
