### ISSUE TITLE
Real Time Monitoring view is either disabled or unavailable

### ISSUE THREAD

**Issue by helloapro** [WISE-Community/WISE#2327]
### Description

Real Time Monitoring view is either disabled or unavailable. There was a menu that's now missing. There was a Teacher view where one could choose an option for the various class periods they were grading (middle school in this example), and now there's no way to toggle Teacher Tools to show any other class periods besides just period #1.

**Operating System:** Windows 10 (most current version of Windows 10)

**Browser:** Chrome (the recommended browser)

### Steps to Reproduce

1. Start a unit
2. Place students in two or more class periods
3. Click on 'Teacher Tools' to see if it will let you see the view of more than one class period

**Expected behavior:** I expect to see all students' work (e.g. 84 students across a total of 4 class periods)

**Actual behavior:** I only can period 1 (e.g. 30 students from just one of the 4 periods I set up)

### Additional Information

I've also been having issues resetting student passwords as needed. Some students are having issues in their view too: They're not being able to log-in with their Google authentication. Some are also getting rerouted when they create an account - they're constantly creating new accounts rather than signing in (this could be user error). 

There's some syncing issues with Google Classroom (not able to assign things from Google Classroom). Is this no longer supported?

I'm assuming there was something that changed with one or more of the updates. Last I worked on my view was back in February 2019. I re-opened my set up to remote teach through this pandemic/lockdown. 

If it helps, this pertains specifically to the Thermodynamics: Heating & Cooling unit.

**Comment by hirokiterashima** [comment]
Hi @helloapro

We recently updated the server and changed the URL (website address) for the teacher tool, so this may be related to the issue that you're seeing. What is the URL that you see in the address bar when you launch the teacher tool? It should look like "https://wise.berkeley.edu/teacher/manage/unit/XYZ", where XYZ is the id of the unit. If you don't see this, you can try closing your browser and reloading the homepage.

If this doesn't work, you may need to clear your browser’s cached data and files. You can find instructions on how to clear the browser cache here
https://support.google.com/accounts/answer/32050?co=GENIE.Platform%3DDesktop&hl=en

**Comment by helloapro** [comment]
Hi Hiroki - thank you for your quick response! Yes, the URL doesn’t appear to be formatted correctly. I’m messaging on behalf of a teacher who has cleared cache and is still not able to access the right filtering for Teacher Tools. Any other possible remedies?

**Comment by hirokiterashima** [comment]
Hi @helloapro,

I'd recommend trying a different browser/device. You can also browse through past Q&A threads for clues here: https://wise-discuss.berkeley.edu

If you're still having issues, please fill out a contact ticket from the WISE website with information about the unit and the teacher username, and we can help you and your teacher privately. It may be an issue that is specific to the unit.
