### ISSUE TITLE
Show vlewrapper and webapp version info of deployed apps

### ISSUE THREAD

**Issue by geoffreykwan** [WISE-Community/WISE#25]
We need a way to see which revisions of code the deployed webapp and vlewrapper are using.

vlewrapper: clicking on the "WISE4.0 Beta should popup a window with the version info"

webapp: credits page, bottom, below "special thanks to"

Google Code Info:
Issue #: 24
Author: honchikun
Created On: 2010-09-29T19:27:57.000Z
Closed On:

**Comment by hirokiterashima** [comment]
This WISE version number is displayed at the bottom of contact us page:
https://wise.berkeley.edu/contact/contactwise.html
