### ISSUE TITLE
Notebook report: save time shows "Invalid date"

### ISSUE THREAD

**Issue by hirokiterashima** [WISE-Community/WISE#2520]
### Description

In the student report, save time shows "Invalid date" 

### Steps to Reproduce

1. Check out commit f552522355b8b0b6a7b46694381d691eca37d0a3 and build
2. Log in as student and open report.
3. Save work

**Expected behavior:** 
The date next to save button should say "Saved just now"

**Actual behavior:** 
The date next to save button says "Saved Invalid date"

<img width="449" alt="Screen Shot 2020-08-10 at 9 41 50 AM" src="https://user-images.githubusercontent.com/119416/89808181-9bd94300-daee-11ea-84e1-08dbcd2e40fb.png">

### Additional Information
It was working at this commit: ad39773e785d28a5ab3c73bfe6ce12d656cd948b on Aug 5.
It stopped working at this commit: f552522355b8b0b6a7b46694381d691eca37d0a3 on Aug 5.

**Comment by breity** [comment]
Fixed by #2484.
