### ISSUE TITLE
Authoringtool session timeout error

### ISSUE THREAD

**Issue by geoffreykwan** [WISE-Community/WISE#253]
hitting "Renew Session" in AT produces this request:
GET http://wise4.berkeley.edu/vlewrapper/vle/undefined
	
404 Not Found

Session is not renewed as a result.

Google Code Info:
Issue #: 252
Author: honchikun
Created On: 2011-08-03T22:58:38.000Z
Closed On:

**Comment by hirokiterashima** [comment]
fixed a while ago. no longer an issue.
