### ISSUE TITLE
renew session controller

### ISSUE THREAD

**Issue by geoffreykwan** [WISE-Community/WISE#254]
Create a controller that renews session for users. should return:

1) OK   if session was renewed successfully.
2) ERROR   if there was an error renewing session.

Use the return values to direct WISE users to appropriate pages.

Google Code Info:
Issue #: 253
Author: honchikun
Created On: 2011-08-04T00:11:53.000Z
Closed On:

**Comment by hirokiterashima** [comment]
This is handled by the SessionManager in VLE
