### ISSUE TITLE
Easy way to update WISE4

### ISSUE THREAD

**Issue by geoffreykwan** [WISE-Community/WISE#26]
Need a way for WISE4 server admins to update WISE4 easily with the latest versions of webapp and vlewrapper. They also need to know that the version is stable or not.

Start off with a document and include a script that Berkeley uses to update its software on slicehost

Google Code Info:
Issue #: 25
Author: honchikun
Created On: 2010-09-29T19:30:52.000Z
Closed On:

**Comment by hirokiterashima** [comment]
We now do a pretty good job providing this information on our Release Notes, https://github.com/WISE-Community/WISE/wiki/WISE4-Release-Notes
