### ISSUE TITLE
Adding an image to a component rubric adds the image twice

### ISSUE THREAD

**Issue by geoffreykwan** [WISE-Community/WISE#2612]
### Description

1. Sign in as a teacher
1. Open a project in the Authoring Tool
1. Open a step
1. Add a component or use an existing component
1. Open the advanced view for the component authoring
1. Click on the "Edit Rubric" button
1. Click the "Insert Asset" button in the rubric authoring
1. Add an image or choose an existing image
1. The image will be added twice to the rubric when it should only be added once

**Comment by hirokiterashima** [comment]
I can't reproduce this. Tried Chome and Firefox and on various components.

**Comment by geoffreykwan** [comment]
Looks like this issue was resolved when we converted all our events to observables.
