### ISSUE TITLE
Fix warning on tomcat startup

### ISSUE THREAD

**Issue by geoffreykwan** [WISE-Community/WISE#39]
INFO: validateJarFile(/....../vlewrapper/WEB-INF/lib/servlet-api-2.5.jar) - jar not loaded. See Servlet Spec 2.3, section 9.7.2. Offending class: javax/servlet/Servlet.class

Not sure what this is or why this is printed. look into it

Google Code Info:
Issue #: 38
Author: honchikun
Created On: 2010-10-07T01:14:10.000Z
Closed On:

**Comment by hirokiterashima** [comment]
yupp. closing old issue.
