### ISSUE TITLE
Allow run owners to choose shared users who can view student names

### ISSUE THREAD

**Issue by breity** [WISE-Community/WISE#405]
This is a tricky one with our human subjects issues, but we probably should have an option where shared teachers can see student names instead of just workgroup number.  It's really inconvenient if teachers are working together but only one account is allowed to see the names.  It's only really for researchers with privacy constraints that the names need to be hidden.

Maybe we should make this an additional option in the sharing dialog?

**Comment by hirokiterashima** [comment]
Option 1 was implemented.
