### ISSUE TITLE
Show total score for workgroup in grading tool

### ISSUE THREAD

**Issue by breity** [WISE-Community/WISE#407]
We should show an aggregate total score, along with the total possible points, for each workgroup in the grading tool.  Teachers need to be able to see overall performance when doing tasks like recording student scores in their grade books or LMS systems.

We need to also decide whether to automatically input auto-graded scores to the teacher scores for steps or not.

**Comment by hirokiterashima** [comment]
This was for WISE4, we're focusing on WISE5 now.
