### ISSUE TITLE
Improve student workgroup management page

### ISSUE THREAD

**Issue by breity** [WISE-Community/WISE#409]
Along with integrating the workgroup management page into the new monitor/grading tool, we should make the alert that users see when deleting a workgroup about possible data loss more clear (see this thread: https://groups.google.com/forum/#!topic/wise4-dev/bbytvDmDoao).  Better yet, we should keep a record of deleted workgroups in the student management interface and maybe provide the option to view student work for deleted workgroups in the grading tool.

A UI refresh is also needed, to go along with new grading tool.

**Comment by breity** [comment]
Leave as is for wise4, will be implemented in wise5.

**Comment by breity** [comment]
This will be done in the portal redesign that we have planned.

**Comment by hirokiterashima** [comment]
This will be part of the angularjs -> angular redesign
