### ISSUE TITLE
Provide teachers with a way to manage all previous students

### ISSUE THREAD

**Issue by breity** [WISE-Community/WISE#428]
Teachers find it very inconvenient to have to un-archive a run to find previous student user names and/or be able to change their passwords.  We should provide a way for teachers to manage all students that have been a part of their previous runs - without having to view the runs themselves.  So, create some sort of database of teachers' students that they can browse, search through, and edit.

This was a very highly requested feature in out June 2014 teacher workshop.

**Comment by breity** [comment]
Will implement when we redesign student management for wise5.

**Comment by hirokiterashima** [comment]
This will be part of the angularjs -> angular redesign
