### ISSUE TITLE
Remove commons-fileupload dependency

### ISSUE THREAD

**Issue by hirokiterashima** [WISE-Community/WISE#435]
We should instead just use Spring's fileupload.

**Comment by tenablesecurity** [comment]
Any update on if this has made it into an official release?

**Comment by hirokiterashima** [comment]
Hi @tenablesecurity thanks for the follow-up. I resolved this by replacing commons-fileupload dependency with spring's fileupload, and by removing the /authorize endpoint. This should resolve the issue and will be in 5.2.1.

**Comment by tenablesecurity** [comment]
Excellent, thank you!
