### ISSUE TITLE
Researcher ROLE bug: loginAs teacher, cannot grade

### ISSUE THREAD

**Issue by geoffreykwan** [WISE-Community/WISE#44]
<b>What steps will reproduce the problem?</b>
1. log in as user with researcher role
2. log in as a teacher
3. try to grade

<b>What is the expected output? What do you see instead?</b>
should be able to grade
grading does not load completely.

Google Code Info:
Issue #: 43
Author: honchikun
Created On: 2010-10-11T18:13:16.000Z
Closed On:

**Comment by hirokiterashima** [comment]
This is no longer an issue.
