### ISSUE TITLE
MySystem2 import draw stepwork as background: if draw has uploaded image, it won't display as background

### ISSUE THREAD

**Issue by hirokiterashima** [WISE-Community/WISE#442]
How to reproduce:
1. In draw step, upload an image from computer. Use other drawing tools like labels and circles and rectangles and do some more work.
2. Go to Mysystem2 step that imports draw step work from step 1 as background. The circles and rectangles and other work shows up but not the uploaded image.

**Comment by geoffreykwan** [comment]
Draw step backgrounds and uploaded images now show up in MySystem2 steps when importing draw work into a MySystem2 step.
https://github.com/WISE-Community/WISE/commit/ab493927e62352634801039b092856ebe04db807
