### ISSUE TITLE
Allow WISE instances to specify project metadata fields

### ISSUE THREAD

**Issue by hirokiterashima** [WISE-Community/WISE#444]
Right now the possible curriculum subject array (e.g. "Earth Science", "Life Science", etc) is hard-coded in the controllers and jsp pages, so there is no easy way for WISE instances to customize them. For example, some people may want to use WISE for math, where possible subjects would be: [Algebra, Geometry, Calculus...], 

Allow each WISE instance to customize the curriculum subjects

**Comment by breity** [comment]
Generalizing to project metadata fields, not just subjects.  Will look at when we redesign the library for wise5.

**Comment by hirokiterashima** [comment]
Implemented and committed https://github.com/WISE-Community/WISE/commit/f354e19512d41055d451d07692bac4673bf886da
