### ISSUE TITLE
tag: mustCompleteBeforeAdvancing problem with branching

### ISSUE THREAD

**Issue by jonvitale** [WISE-Community/WISE#471]
When a "mustCompleteBeforeAdvancing" tag map is placed on a step within a branch students in the second branch are unable to proceed because they are affected by the constraint in the first branch.

For example if step 2.2.1 and step 2.3.1 both have the mustCompleteBeforeAdvancing, users are prevented from navigating to 2.3.1 because the constraint has not been released by step 2.2.1, which is "before" 2.3.1. Therefore, if we are branching by workgroup, only half of the students can proceed through the unit.

**Comment by geoffreykwan** [comment]
This is for WISE4 and we are trying to move away from WISE4 and focus more on WISE5.
