### ISSUE TITLE
Flash step does not repopulate student work anymore

### ISSUE THREAD

**Issue by geoffreykwan** [WISE-Community/WISE#486]
Flash student work is saved to the server but when you revisit the flash step, the student work isn't repopulated. You can test it out on production by logging in as aa11 and launching

Title: Example Project
Access Code: Mole272
Run Id: 6546

Go to Step 1.33: Flash Step and add a label and visit another step and come back and the work will not be repopulated.

**Comment by hirokiterashima** [comment]
closed. specific to flash model
