### ISSUE TITLE
Can't edit max scores in Firefox

### ISSUE THREAD

**Issue by hirokiterashima** [WISE-Community/WISE#487]
Throws a js error:
TypeError: event.srcElement is undefined classroomMonitorView_main.js:3447

**Comment by hirokiterashima** [comment]
Firefox 35, OSX Yosemite 10.10.1

**Comment by geoffreykwan** [comment]
Fixed
https://github.com/WISE-Community/WISE/commit/1ca8559d1024f25304fb5d1b73c4ac7580ceb42d
