### ISSUE TITLE
New authoring tool: Open project settings/metadata interface on first load

### ISSUE THREAD

**Issue by breity** [WISE-Community/WISE#488]
We might want to show the project info and settings interface when an author first opens a new or copied project.  This would ensure authors complete the required fields and also that they review any customizations (like Idea Manager terminology) to ensure they work for this new project.

Since Idea Manager terminology is overwritten by each project instance, copied projects will inherit the parent project's terms (see issue #478).  Terms then may be in the wrong language, for example.  This would help mitigate that problem.  We could also provide a "revert" or "default" option for customizable terms as well, which would provide internationalized values if available.

**Comment by geoffreykwan** [comment]
This is for WISE4 and we are trying to move away from WISE4 and focus more on WISE5.

**Comment by breity** [comment]
This actually applies to WISE5 too. I think we should encourage authors of new projects to add metadata to their projects (and perhaps indicate a set of required fields). As mentioned in the issue contents, this would also help ensure that authors update copied projects on first load.

**Comment by hirokiterashima** [comment]
We will consider this when re-writing the AT in Angular
