### ISSUE TITLE
Homepage: focus on username textbox on page load

### ISSUE THREAD

**Issue by hirokiterashima** [WISE-Community/WISE#496]
When the main home page loads, focus on the username textbox.

**Comment by breity** [comment]
Not sure if this is the best idea in all cases.  On tablets and mobile phones, for example, this would automatically open up the on-screen keyboard and obscure the rest of the page.  That wouldn't be ideal for people wanting to actually browse the WISE site and look at informational content.  We could just focus for non-touch screens.  I'll think about it for when we redesign the homepage for wise5.

**Comment by hirokiterashima** [comment]
Good point. It could get annoying for touch device users. Let's think about this some more.

**Comment by breity** [comment]
Probably best not to do this.  Closing.
