### ISSUE TITLE
Questionnaire after Java step does not load

### ISSUE THREAD

**Issue by geoffreykwan** [WISE-Community/WISE#50]
Elissa and I noticed today that when a questionnaire step follows a Java step, it tends to not load. This happens often in GCC, and was happening in 4.8 of plate tectonics as well. Otherwise the questionnaire steps seem to load okay. 

Just thought it might be helpful to share this insight- not sure if there is a fix for it.

Google Code Info:
Issue #: 49
Author: honchikun
Created On: 2010-10-13T00:13:11.000Z
Closed On:

**Comment by hirokiterashima** [comment]
Closing. We don't support java steps anymore.
