### ISSUE TITLE
Contact WISE error message when recaptcha keys are not set

### ISSUE THREAD

**Issue by hirokiterashima** [WISE-Community/WISE#501]
When the 
recaptcha_public_key and recaptcha_private_key keys are not set in wise.properties and you go to Contact WISE page, you will see this message:

Input error: k: Format of site key was invalid

We should not show the message if the keys are not set. The form seems to work normally even if the keys are not set.

**Comment by geoffreykwan** [comment]
Done
https://github.com/WISE-Community/WISE/commit/300890711846dca34b10c15f9a03404aa96a5983
