### ISSUE TITLE
Students can still create workgroups with more than 3 students

### ISSUE THREAD

**Issue by geoffreykwan** [WISE-Community/WISE#504]
Here's how to reproduce the problem
1. Student aa11 launches the project and gets to the classmate sign in page
2. Student aa11 enters aa11, bb11, cc11 into the 3 classmate entries
3. Student bb11 is on another computer and launches the project and gets to the classmate sign in page
4. Student bb11 enters bb11, aa11, dd11 into the 3 classmate entries
5. Student aa11 clicks "Run Project" to create the workgroup and start the project
6. Student bb11 clicks "Run Project" to create the workgroup and start the project
7. Now aa11, bb11, cc11, and dd11 are all in the same workgroup

**Comment by breity** [comment]
Duplicate.
