### ISSUE TITLE
Teacher-Shared projects shouldn't show up in main homepage

### ISSUE THREAD

**Issue by hirokiterashima** [WISE-Community/WISE#514]
Request by Doug K.

They should show up in the library, but not in the main homepage project listings because it hasn't gone through rigorous review.

**Comment by breity** [comment]
Yeah, this is true.  We should only have the reviewed projects in the
public library and then have the teacher-contributed projects only show up
in the library once you're signed in as a user.  And we'll need to finalize
some verbiage/disclaimer text for the user-contributed items in the WISE 5
library.

**Comment by hirokiterashima** [comment]
The solution is to add just the "library" and "teachershared" tags.

If you add just "library" to a project, it will show up in the library, but not in the main home page.
If you add "library" and "public" to a project, it will show up in the library and in the main home page.

So for the teacher-shared projects, I added "teachershared" and "library". This caused the projects to show up in the library page under "teacher-shared projects", but not in the main home page.
