### ISSUE TITLE
When post data is too large make notification to student more obvious

### ISSUE THREAD

**Issue by hirokiterashima** [WISE-Community/WISE#515]
When student tries to save the data and the data size exceeds the amount specified in wise.properties, students sees a blurb at notification bar at the top, which can easily be missed.

Make it more obvious to the student that the data was not saved, and they have to reduce their work. Maybe this should be a popup.

**Comment by breity** [comment]
Add this in WISE5, keep it like it is in wise4.

**Comment by hirokiterashima** [comment]
this was for wise4, won't fix.
