### ISSUE TITLE
VLE4: Branching based on random number

### ISSUE THREAD

**Issue by hirokiterashima** [WISE-Community/WISE#521]
Request by Jon V, would like to have ready for testing by end of day April. 13.

We need a way to branch based on a random number. We should use a random function, random(numbeOfBranches), and map the result to the paths.

e.g.
branch point: [path A, path B]  = > random(2)
branch point: [path X, path Y, path Z]  => random(3)

**Comment by geoffreykwan** [comment]
Done
https://github.com/WISE-Community/WISE/commit/964708c4c01cd5bea8d45f5ae76e3a3b1c25fca8
