### ISSUE TITLE
WISE5: Show Total Scores for student

### ISSUE THREAD

**Issue by hirokiterashima** [WISE-Community/WISE#539]
Show scores in the map and in the step view

**Comment by hirokiterashima** [comment]
depends on https://github.com/WISE-Community/WISE/issues/540

**Comment by geoffreykwan** [comment]
The scores already show up in the step view. The total and max score for the project does not currently show up in the UI but the values are available in vleController.totalScore and vleController.maxScore. All you need to do is decide where you want those values to show up in the map view. I'll leave that up to you.

**Comment by breity** [comment]
Okay, I added total score to the account menu dropdown in the WISE5 default theme. I still need to finish adding total scores for each step (both in step view and navigation) and for each activity (in the navigation). But I'll close this and create a new issue for the 5.1 milestone.

**Comment by breity** [comment]
Closed with 56235b5.

**Comment by breity** [comment]
Closed with 56235b5.
