### ISSUE TITLE
Converter: strip out ./assets

### ISSUE THREAD

**Issue by hirokiterashima** [WISE-Community/WISE#545]
After this change: https://github.com/WISE-Community/WISE/commit/5838266bb8c4cb18ea4539b06063dccde1fdf019, the converted project.json should no longer contain ./assets/... when referencing resources in the assets folder.

**Comment by geoffreykwan** [comment]
Completed
https://github.com/WISE-Community/WISE/commit/055616c4704d970b719b54c48b348b953a5a07bd
