### ISSUE TITLE
Make components and features that use drag-and-drop accessible

### ISSUE THREAD

**Issue by breity** [WISE-Community/WISE#549]
We should ensure that drag-and-drop components have WAI-ARIA compliance.  This means providing an alternate method of selecting and moving items (using the keyboard, for example).

**Comment by breity** [comment]
Look into using Drag and Drop from Angular Material: https://material.angular.io/cdk/drag-drop/overview.

**Comment by hirokiterashima** [comment]
We will re-implement the components Angular Material's drag-and-drop when we switch AngularJS->Angular
