### ISSUE TITLE
Update WISE5.org logo image

### ISSUE THREAD

**Issue by hirokiterashima** [WISE-Community/WISE#557]
Right now, when you go to wise5.org, the logo says "wise4.org":

<img width="1060" alt="screen shot 2016-02-16 at 3 12 03 pm" src="https://cloud.githubusercontent.com/assets/119416/13094491/c19d64f2-d4bf-11e5-9d17-431f96e4f9f2.png">

We'll phase out wise4.org in the next year so we need to update this.

Maybe it shouldn't mention the version number and just say "WISE"?

**Comment by breity** [comment]
I update the logo to say wise5.org for now.  Perhaps we should use a different url that is version-proof, though for the future.
