### ISSUE TITLE
HTTP Status 404 - /wise/portal/admin/account/enableDisableUser.jsp

### ISSUE THREAD

**Issue by dougti** [WISE-Community/WISE#563]
The "Enable/Disable User" link under "User Management" points to "enableDisableUser.jsp", however the file itself is all in lower case causing a 404.

For the time being, it was easier for me to just rename the file than update the links.

`mv webapps/wise/portal/admin/account/enabledisableuser.jsp webapps/wise/portal/admin/account/enableDisableUser.jsp`

**Comment by hirokiterashima** [comment]
Thanks for creating the issue @dougti.
If you'd like, you can also make the change yourself and create a pull request in the future.
