### ISSUE TITLE
Bug only on server: "Saved 3 minutes ago" instead of "Saved just now"

### ISSUE THREAD

**Issue by hirokiterashima** [WISE-Community/WISE#567]
This is a bug that happens on production. I don't see this locally.

How to reproduce:
1. Go to step with a save or submit button.
2. Do some work, and hit save or submit.

It will save "Saved/Submitted 3 minutes ago". See screenshot below.

What it should say: "Saved just now".

![screen shot 2016-03-08 at 5 35 47 pm](https://cloud.githubusercontent.com/assets/119416/13622613/b90ccf94-e554-11e5-87a3-ad714cc85eed.png)

**Comment by breity** [comment]
Hmm, strange.  Only happens in a run, it seems.  Previewing projects works fine.  The step/component displays the server time from the latest component state when in a run.  I wonder how that could be 3 minutes behind.

**Comment by hirokiterashima** [comment]
The server clock and local clock are off by ~3 minutes so we're seeing this issue. I think we should use the clientSaveTimestamp to display this information.

**Comment by breity** [comment]
Ah, that makes sense.  Yeah, @geoffreykwan and I talked about whether to use client vs server time for these.  The problem with client time is that client times can vary, especially if students switch computers.  Client clocks could be set incorrectly, so when the save times are displayed on different machines, the times could be off.  We figured server time was at least consistent for the most part.  What do you think?

**Comment by hirokiterashima** [comment]
Using the server time is fine as long as we calculate the offset before displaying the time, which could get a bit hairy.

I still think using the client timestamp is ok in this particular case.

**Comment by geoffreykwan** [comment]
Changed the save message back to using the client save time.
https://github.com/WISE-Community/WISE/commit/ad9ccc38624ba0c67531468906be4e9b543674bc

**Comment by breity** [comment]
Thanks. Yeah I think this okay for now. We can revisit later on. I just updated all the components to use clientSaveTime too.
