### ISSUE TITLE
Discussion component: add anonymous option

### ISSUE THREAD

**Issue by breity** [WISE-Community/WISE#568]
I'm wondering if we should allow authors to make discussions anonymous.  Authors could specify whether or not they want student names to appear on posts.  I think teachers would be able to see workgroup names in all cases, but students would not if the component was set to anonymous (except for maybe their own names).

**Comment by breity** [comment]
Yep, I was thinking something just like that.  Or use animals or some other
category like we do for the run access codes.  So "Team Otter", "Team
Penguin", etc.


On Thu, Mar 10, 2016 at 11:43 AM Hiroki Terashima <notifications@github.com>
wrote:

> This would be a useful feature.
> We can also use randomly-chosen names ["bart", "homer", "marge", ...] so
> that the students can follow the thread better across posts and steps.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/WISE-Community/WISE/issues/568#issuecomment-195015415>
> .
>
-- 
Jonathan Lim-Breitbart

**Comment by hirokiterashima** [comment]
this will be part of angularjs -> angular redesign
