### ISSUE TITLE
WebAudio embedded component

### ISSUE THREAD

**Issue by hirokiterashima** [WISE-Community/WISE#570]
Create a WebAudio embedded component that allows students to change the frequency and hear the sound.

Here's an open-source project that does what we need: http://webaudioplayground.appspot.com. 

I think we just need parts of this app as a stand-alone HTML application and then we can embed that using the Embedded Component.

**Comment by geoffreykwan** [comment]
Completed
https://github.com/WISE-Community/WISE/commit/34f7044d753488202db3284551c2fa70caa2d1c4
