### ISSUE TITLE
WISE4->WISE5 Project Converter in the Authoring Tool

### ISSUE THREAD

**Issue by hirokiterashima** [WISE-Community/WISE#571]
In the extras section of the WISE4 authoring tool, add a "Convert to WISE5" button.

If the user has the right permissions, clicking on it will convert the project to WISE5 using the wise4To5ProjectConverter.js and return a new WISE5 project id.

Then the WISE4 authoring tool should close and the WISE5 authoring tool should open with the new project id.

**Comment by hirokiterashima** [comment]
Also add a section on the documentation that explains this process for existing WISE4 instance administrators.

**Comment by geoffreykwan** [comment]
Completed
https://github.com/WISE-Community/WISE/wiki/WISE4-to-WISE5-Project-Conversion
