### ISSUE TITLE
reorganize teacher guides, make it easy to access and find stuff inside

### ISSUE THREAD

**Issue by geoffreykwan** [WISE-Community/WISE#58]
More and more teachers => need for better help system

Organize Teacher Guides
- getting started guide
- FAQ

Make it easy to find stuff on it.

Google Code Info:
Issue #: 57
Author: honchikun
Created On: 2010-10-18T23:19:03.000Z
Closed On:

**Comment by hirokiterashima** [comment]
This was for WISE4, we've already completed AT help documentation and are planning a CM help documentation for WISE5.
