### ISSUE TITLE
Output encoding problem in Excel

### ISSUE THREAD

**Issue by hirokiterashima** [WISE-Community/WISE#597]
Report from Nathan Z:

I encounter a problem with the output of WISE. The Chinese characters are not properly encoded when the file is opened with Excel. However, the encoding is correct if I opened the file with TextEdit or NoteBook. Please see the attachment for encoding problem. 

![screen shot 2016-04-04 at 11 56 59 pm](https://cloud.githubusercontent.com/assets/119416/14287601/20e177f0-fb08-11e5-8357-61e1072129a7.png)

@geoffreykwan any ideas? It looks like it's the step title that is in Simplified Chinese and not being rendered correctly.

**Comment by geoffreykwan** [comment]
Nathan said his colleagues were able to view Chinese characters in the excel files. This problem may have been due to system language settings and not having the Chinese language font.
