### ISSUE TITLE
Let embedded components control annotations display?

### ISSUE THREAD

**Issue by breity** [WISE-Community/WISE#608]
We might want to let embedded components control the display of annotations so that it matches the embedded components' layout, style, etc.  Right now, we show the feedback below the embedded component's iframe using the ComponentAnnotations app component.

We could add a setting to the embedded component's json content that controls whether the default annotations are displayed.  We'd also need to pass in the maxScore and latest annotations to the embedded app.

**Comment by geoffreykwan** [comment]
We implemented the ability for Embedded models to create annotations as well as retrieve previous annotations in c618a4fbc9e18581ae109a9367b5d58306e92764 a little while ago.
