### ISSUE TITLE
Regular steps in a planning activity should display popup when clicked in planning mode

### ISSUE THREAD

**Issue by geoffreykwan** [WISE-Community/WISE#617]
1. Turn on planning mode in an activity
2. Click on a regular step that is in the planning activity
3. A popup should display that says "You are not allowed to enter the step while in Planning Mode. Turn off Planning Mode to enter the step."

The popup correctly shows up when the student clicks on a planning step but not when they click on a regular step.

**Comment by breity** [comment]
Yeah I actually disabled clicking on regular steps when in planning mode. I
was thinking of doing the same for planning steps too and allowing clicking
for reordering later on. The popup does help to explain why you can't open
a step, so I think I'll add it back for now and think about the ux some
more.

On Tue, Apr 26, 2016, 3:20 PM Geoffrey Kwan <notifications@github.com>
wrote:

>
>    1. Turn on planning mode in an activity
>    2. Click on a regular step that is in the planning activity
>    3. A popup should display that says "You are not allowed to enter the
>    step while in Planning Mode. Turn off Planning Mode to enter the step."
>
> The popup correctly shows up when the student clicks on a planning step
> but not when they click on a regular step.
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/WISE-Community/WISE/issues/617>
>
-- 
Jonathan Lim-Breitbart

**Comment by breity** [comment]
Done in b393d91.
