### ISSUE TITLE
Image attachments to discussion posts appear stretched.

### ISSUE THREAD

**Issue by hirokiterashima** [WISE-Community/WISE#620]
The images appear overly-stretched once they're posted.

![screen shot 2016-05-02 at 5 44 56 pm](https://cloud.githubusercontent.com/assets/119416/14972086/b6462ed6-108d-11e6-93f4-55ae5546e29c.png)

**Comment by hirokiterashima** [comment]
I think it's a recent change. Lauren reported it today.

**Comment by breity** [comment]
Yep, looks like the Angular Material update caused this.  Fixed in 	e0c97ba.
