### ISSUE TITLE
Preview project without constraints

### ISSUE THREAD

**Issue by hirokiterashima** [WISE-Community/WISE#626]
Request from LA:
Can we get a "view without constraints" option? I want to look at activities below the planning activity, but they are locked. I know I can look through the authoring tool, but even that I can only do one step at a time.

**Comment by hirokiterashima** [comment]
@geoffreykwan didn't you finish this earlier?

**Comment by geoffreykwan** [comment]
@hirokiterashima Yea, I completed it with this commit. I'll close this now.
https://github.com/WISE-Community/WISE/commit/9bb0753e03675e142859233b98dbb0d2ee97662a
