### ISSUE TITLE
Match Component: Allow option to sort horizontally

### ISSUE THREAD

**Issue by geoffreykwan** [WISE-Community/WISE#642]
Place the source bucket on the left and the target buckets on the right.

**Comment by breity** [comment]
I'm planning on removing angular-ui-tree in Match steps and using angular-dragula to power the drag and drop. I'll update the ui visuals to go along with that, so I can add in the horizontal sort option then too.

**Comment by breity** [comment]
Resolved by commit 4e91b6e.  Still need to add an option to the Match component authoring interface.
