### ISSUE TITLE
Don't show student names in grading tool for shared teachers

### ISSUE THREAD

**Issue by hirokiterashima** [WISE-Community/WISE#649]
Request by Libby

The researchers who were shared the run should not be able to see student names in the classroom monitor tool. 

This should be an option. See student names true/false in the future, but for now, as we did in WISE4, assume that shared teachers with READ permissions should not be able to see student names.

**Comment by geoffreykwan** [comment]
Completed
https://github.com/WISE-Community/WISE/commit/5206cd3c705d664fbc2d5e93da4fafdfb69ae118
