### ISSUE TITLE
Allow students to add Open Response work to the notebook

### ISSUE THREAD

**Issue by geoffreykwan** [WISE-Community/WISE#663]
This would be like clipping an Open Response component.

**Comment by breity** [comment]
This could eventually be covered by the ability to highlight text and add it to a note, as we've discussed before. Grabbing the component response text is certainly the more straightforward option right now.

**Comment by hirokiterashima** [comment]
For this issue, we'll add a "Add to Notebook" button for the Open Response component.

**Comment by hirokiterashima** [comment]
assigned to Geoff

**Comment by geoffreykwan** [comment]
Completed https://github.com/WISE-Community/WISE/commit/afce40ea51769c4a10ea823d0cef9e740d5e6fdf
