### ISSUE TITLE
label component authoring: adding new label hides preview canvas

### ISSUE THREAD

**Issue by hirokiterashima** [WISE-Community/WISE#678]
Steps to reproduce (in AT):
1. create a new label component. 
2. click on "add label" button.

In the preview section (below), the prompt and the "Add a Label" button is there, but the canvas where the background and labels should be disappears.

**Comment by geoffreykwan** [comment]
Fixed
https://github.com/WISE-Community/WISE/commit/7980071ca143d583d5e0ec2a44220c694fc4401a
