### ISSUE TITLE
Make the height of step select (and other) dropdown menus dynamic based on window height

### ISSUE THREAD

**Issue by breity** [WISE-Community/WISE#679]
Right now, the step select is a dropdown menu (md-menu), which only shows about 5 items or so without having to scroll:
![item-select](https://cloud.githubusercontent.com/assets/297450/18883008/6c96c2dc-8496-11e6-9695-bc041932989c.png)

The md-menu should be replaced with a sidebar (md-sidebar) that takes up the full height of the browser window.

**Comment by hirokiterashima** [comment]
@geoffreykwan increased the height of the menu. We will revisit when rewriting the VLE in Angular 2019
