### ISSUE TITLE
Selective Notification

### ISSUE THREAD

**Issue by geoffreykwan** [WISE-Community/WISE#68]
From Vanessa:

Description: It would be great if there was a way for me to get a notification when a teacher sets up a run I need to know about. Here is how (as a user) I'd see it happen, in my ideal dream world:

I know I need to visit Ariel's class while she runs the 6th grade curricular projects. I email and email but she is busy and might forget to let me know. WISE is awesome and let's me set up the following: Alert me if: [ArielOwen1;ArielOwen;ArielOwen2]Sets up run of [Thermodynamics;Plate Tectonics; Global climate change]

Google Code Info:
Issue #: 67
Author: honchikun
Created On: 2010-10-25T16:51:43.000Z
Closed On:

**Comment by breity** [comment]
Should be part of new portal redesign and community features.  "Follow a WISE teacher" or something like that, if user has opted in to being followed.
