### ISSUE TITLE
Calculate revision count in student VLE and save it in the student status

### ISSUE THREAD

**Issue by geoffreykwan** [WISE-Community/WISE#683]
A step visit that has any new component states will be considered as a new revision.

**Comment by geoffreykwan** [comment]
This doesn't seem to be needed anymore. The classroom monitor is able to calculate the revision count by getting all the student work.

**Comment by breity** [comment]
I think the idea here might have been so that we didn't need to get all the student work initially, but just the latest version and then get all the revisions when teachers or students want to view them. (We also want to let students review their revisions in the VLE eventually.)
