### ISSUE TITLE
WISE5 AT: Wizard for Branching

### ISSUE THREAD

**Issue by hirokiterashima** [WISE-Community/WISE#690]
Implement a simple wizard for authors to add branching to their project.

We can follow similar steps for authoring transitions and constraints:
1. choose branch point
2. choose branch criteria (score, workgroup, random)
3. create paths and put steps in the paths
4. map the criteria to paths
5. submit

Constraints (branchPathTaken) should be added and the transitions should be updated.

**Comment by geoffreykwan** [comment]
Completed
https://github.com/WISE-Community/WISE/commit/ef2270477948ff7809cd5deb95ab9ed50075c89c
