### ISSUE TITLE
CM: student grading left side partially covered by menu

### ISSUE THREAD

**Issue by hirokiterashima** [WISE-Community/WISE#692]
How to reproduce:
1. open classroom monitor for WISE5 run
2. go to student progress view
3. select a team.

What you see: menu on the left is displayed over the student grading view and covers the view.
![screen shot 2016-11-10 at 10 21 46 am](https://cloud.githubusercontent.com/assets/119416/20188882/9881728c-a72f-11e6-88e5-433ad01579d6.png)

**Comment by breity** [comment]
Yeah, I haven't worked on the grade by student view yet at all.  We're considering actually leaving it out altogether in the new Classroom Monitor and just use step grading, as that is what most teachers use.  We still want a way to show an overview of a team's progress and quick links to their work.  So perhaps a filter that lets you look at one workgroup at a time (in addition to the period filter) in the nodeProgress and nodeGrading views might be the solution.  But I'm thinking that simplifying to one grading interface is best.

**Comment by hirokiterashima** [comment]
we got rid of grade-by-student.
