### ISSUE TITLE
W5 CM accountMenu not found 404 error

### ISSUE THREAD

**Issue by hirokiterashima** [WISE-Community/WISE#703]
The W5 Classroom Monitor's account menu doesn't open.

There's an error in the js console:
http://localhost:8080/wise/wise5/classroomMonitor/templates/accountMenu.html 404 (Not Found)

It'd be good if we can get it in there for v5.3.

**Comment by breity** [comment]
Yep, it's just because I haven't made it yet. :) Will add it for 5.3.

**Comment by breity** [comment]
Removing the reference to the template file for now. Will add the CM account menu in 5.5.
