### ISSUE TITLE
CM: student's ConceptMap diagram showing up for wrong student

### ISSUE THREAD

**Issue by hirokiterashima** [WISE-Community/WISE#710]
I'm seeing this weird behavior in the CM where it is showing the work for the wrong set of students:

run: 10562
step: 4.6, build your mysystem

bb,tt has not visited the step, but it is showing work that ht did.
ht has visited the step and done the work, but it doesn't show the work.

Any idea what's going on?

Other steps seem to be showing the correct work for the correct student.

**Comment by hirokiterashima** [comment]
What seems to be going on is that the states are always drawn on the first ConceptMap canvas. So if there are 3 students, all three students' work will be drawn on the first student's canvas.

**Comment by geoffreykwan** [comment]
Fixed
https://github.com/WISE-Community/WISE/commit/4eff6dd5aecd1047fc5fea958564ad323befbcc8
