### ISSUE TITLE
Create WISE5 global translation file

### ISSUE THREAD

**Issue by hirokiterashima** [WISE-Community/WISE#726]
Create a global translation file in wise5/i18n directory for storing translation keys that are commonly used across tools (VLE, CM, AT) and components (or, mc, etc).

The keys should be stored in ALL CAPS so it'll be easier to differentiate global keys from local keys.

Then, update the tools and components to reference the new global keys.

**Comment by geoffreykwan** [comment]
Completed
https://github.com/WISE-Community/WISE/commit/bb230889623ce7c982848ca2d3fc0fb3cc724d5e
