### ISSUE TITLE
AT: use summernote for HTML component and Notebook report

### ISSUE THREAD

**Issue by hirokiterashima** [WISE-Community/WISE#733]
(for 5.3.2)

Replace textarea with summernote for HTML component and Notebook report starter HTML. Keep the prompts for other components simple input boxes for now.

**Comment by geoffreykwan** [comment]
Completed
https://github.com/WISE-Community/WISE/commit/2b7cfa5fc7970b03766a13010914b33746e1ee77
https://github.com/WISE-Community/WISE/commit/338b9c68b6ac4325434864f744d23fe893ab16e1
