### ISSUE TITLE
Notebook add note: upload assets section disappears

### ISSUE THREAD

**Issue by hirokiterashima** [WISE-Community/WISE#735]
Reproduced in Safari, Chrome, local and production.

In the add note dialog, the boxed section that is used to upload assets (by clicking on it or by dragging files onto it) shows for a brief moment and then disappears. On rare cases (in my case, when I was logged in as a student for the run) it did not disappear and worked as intended. The notebook's upload assets setting was set to true.

**Comment by breity** [comment]
Ah yes, this was by design originally because note attachments didn't work in preview mode.  Fixing now.

**Comment by hirokiterashima** [comment]
ok thanks.
