### ISSUE TITLE
After a student logs in, we should remove the "Create WISE Account" button at the top right

### ISSUE THREAD

**Issue by geoffreykwan** [WISE-Community/WISE#785]
We should also remove the "New to WISE? Sign up for free." text at the top right after the student logs in.

![wise_header](https://cloud.githubusercontent.com/assets/1036509/23730050/3214fb34-041a-11e7-954c-3db7aa0a7133.png)

**Comment by breity** [comment]
Yep, sure. Might be fine to wait until we work on the WISE site redesign this summer.

**Comment by breity** [comment]
Not necessary now that we have redesigned the site.
