### ISSUE TITLE
Grade-by-step: expand all or render when workgroup is in view

### ISSUE THREAD

**Issue by hirokiterashima** [WISE-Community/WISE#790]
Requested by Robin and ErinG.

Clicking on each student to expand their work in grade-by-step view is tedious. We should either:
1. have an expand-all button that shows all the workgroups' work for the step 
or
2. render workgroup's work when it comes into view (as teacher is scrolling).

I think option 2 is better because it don't require teacher to click on the expand all button.

**Comment by breity** [comment]
Yep, I have the expand/collapse all option in progress.

I do like loading on demand.  The problem with that in this interface is that some teachers won't want all the workgroups to be expanded.  So if you just automatically expand workgroups on scroll, teacher don't have the option to view specific groups at one time.  Also, if they wanted to just grade a team that was at the bottom of the list, they'd have to scroll through every other teams' work to get there.  It would be a huge pain - especially if the step has a lot of content.  It would be a ton of scrolling and could also be a lot of unnecessary waiting.  As it stands now, they only have to scroll through the list of names and choose the one they want to open.  This is why I think #1 makes more sense here.

**Comment by breity** [comment]
Completed with ddf35d72d0dfe5ed1278c8cd70e709e5c5bfb9b7.
