### ISSUE TITLE
Grade-by-Workgroup

### ISSUE THREAD

**Issue by hirokiterashima** [WISE-Community/WISE#791]
Request by ErinG:

Bring back grade-by-workgroup view. For 5.4, it should at the very least display students' work. Some teachers want to look at specific workgroups only.

**Comment by breity** [comment]
Yeah, I'm still against bringing back grade-by-step.  I just feel having two grading interfaces is redundant and confusing.

But I do think we should provide a way to grade/view at one workgroup at a time.  I think a nice way to do this is to add a workgroup select dropdown next to the period select in the step grading view. It would default to "All teams" but would let the teacher choose an individual team if they want.  When a workgroup is selected, all the others will be hidden and the teacher can just use the forward and back arrows to switch steps while still just seeing the selected team.

Teachers could directly access grading for a single workgroup from the student progress table too.  So when they click on a workgroup, it would open up the grading view with that team already selected from the dropdown.  And if we add step scores to the student progress table in the future, clicking on an individual cell in the table could bring the teacher directly to the grading view for that step (with the corresponding workgroup selected).

What do you think?  I can do some quick mockups for this if you like.  I just think bringing back grade-by-step is the wrong solution in terms of UX.

**Comment by hirokiterashima** [comment]
Plan sounds good. Please mock it up and let's discuss.

For now, let's bring back the grade-by-workgroup view until the new tool is in place. There are several teachers who need the functionality in their runs.

**Comment by breity** [comment]
We decided to keep the grade-by-workgroup view removed but let teachers select a team/student from the student progress view which directly opens the grading view with the team selected.
