### ISSUE TITLE
ReCaptcha Key empty string check

### ISSUE THREAD

**Issue by hirokiterashima** [WISE-Community/WISE#803]
Nathan in China reported slow login for teachers. Once they're logged in and see the teacher homepage it's fast again.

Issue: ReCaptcha key validation does not work because they're behind the firewall. Even though they've left recaptcha public/private keys blank in wise.properties, the validation is taking place.

Fix: Don't do any validation when repcatcha public/private keys are empty.

**Comment by geoffreykwan** [comment]
Fixed
https://github.com/WISE-Community/WISE/commit/0b0554b839a622346f1c6b89f9b02ab45c2b188f
