### ISSUE TITLE
CM: Look into lazy-loading components in grade-by-step view

### ISSUE THREAD

**Issue by hirokiterashima** [WISE-Community/WISE#811]
Some steps take a long time to load when teacher expands all workgroups' work because they have large images or embedded models that take long time to render.

See if it's possible to only load the components when they are in view as the teacher scrolls through the grade-by-view and have expanded all workgroups' work.

**Comment by geoffreykwan** [comment]
Completed
https://github.com/WISE-Community/WISE/commit/d149e1d5150472978acac13143c51b0fa626b70f
