### ISSUE TITLE
Step numbering issue for branching across actitivites

### ISSUE THREAD

**Issue by hirokiterashima** [WISE-Community/WISE#828]
See project 20359. It has two paths that span multiple activities and the numbering is off.

![screen shot 2017-04-21 at 2 50 55 pm](https://cloud.githubusercontent.com/assets/119416/25297349/08a5afd2-26a2-11e7-9497-cbdc49eae0e7.png)

**Comment by geoffreykwan** [comment]
Fixed
https://github.com/WISE-Community/WISE/commit/97826fa24f0cf876c6b773c35421865a868ae2fe
