### ISSUE TITLE
W5 AT: moving from inactive step to empty activity fails

### ISSUE THREAD

**Issue by hirokiterashima** [WISE-Community/WISE#837]
How to reproduce:
Moving an inactive step to an activity without any nodes. 

What should happen:
The inactive step should be moved to the activity.

What happens:
Nothing happens visually.

**Comment by geoffreykwan** [comment]
Fixed
https://github.com/WISE-Community/WISE/commit/29cc785c35fdcda5f6c4c17d4401d807a3201d93
