### ISSUE TITLE
TELS Portal Error

### ISSUE THREAD

**Issue by geoffreykwan** [WISE-Community/WISE#85]
When i create project,TELS Portal Error occur as following:"The server has encountered an error.The staff has been informed about this problem.
Please return to your previous page. "

Google Code Info:
Issue #: 84
Author: hxqabc.k...@gmail.com
Created On: 2010-11-11T15:35:15.000Z
Closed On:

**Comment by hirokiterashima** [comment]
Old issue, no longer relevant.
