### ISSUE TITLE
Teacher Preview: show rubrics

### ISSUE THREAD

**Issue by hirokiterashima** [WISE-Community/WISE#855]
Show rubrics if they're logged in as a teacher account.

Show a button to "show/hide teaching tips" in the step bar.
Click on it -> show the rubrics inline.
Step rubrics will show up at the top.
Component rubrics will show up interweaved inside the components.

Click on it again -> hide all inline rubrics.

See if we can get this working for the teacher workshop.

**Comment by geoffreykwan** [comment]
Completed by @breity https://github.com/WISE-Community/WISE/commit/504b496d80b5d3b06bbec0513b23332ffcc55906
