### ISSUE TITLE
Allow sorting projects by tag

### ISSUE THREAD

**Issue by geoffreykwan** [WISE-Community/WISE#87]
Be able to sort projects (in "my projects" section) in the portal by clicking on the tag and either having all of the projects with that tag grouped at the top or only have projects with that tag show up. Requested by Doug.

Google Code Info:
Issue #: 86
Author: geoffrey...@gmail.com
Created On: 2010-11-15T21:57:04.000Z
Closed On:

**Comment by breity** [comment]
done
