### ISSUE TITLE
Add logging to AT

### ISSUE THREAD

**Issue by hirokiterashima** [WISE-Community/WISE#887]
Request from Chunli at ECNU:

1. How teacher operate the project, such as copy, run, share, preview or create?
2. What kind of componnets teacher use, and how they arrange the component?
3. How they operate the activity/step page, such as  create, arrange？And how they import steps form other projects?
4. What page they go through when logining in?
 
I'm doing research about how teacher design WISE project now.  Some Chinese teachers have designed project on our WISE in East China Normal University.  I want to inquire whether there are log files about teachers in the current WISE version.

**Comment by geoffreykwan** [comment]
Events are now saved for the most common actions in the Authoring Tool. We may want to add more specific events later.
https://github.com/WISE-Community/WISE/commit/b8635dc7657d978fc0ee58091d0fbdaa86870b38
