### ISSUE TITLE
Change default # of branch paths to 2?

### ISSUE THREAD

**Issue by hirokiterashima** [WISE-Community/WISE#904]
Right now when you create a new branch from a step, the default number of branch paths is set to 1.

![screen shot 2017-09-20 at 3 10 56 pm](https://user-images.githubusercontent.com/119416/30670143-0cf761b6-9e16-11e7-8eb2-8bf2184a5dbd.png)

Shouldn't this be 2? Would someone ever want to create a 1 path branch?

**Comment by geoffreykwan** [comment]
The number of branch paths field is actually a reflection of how many transitions the step currently has so we don't want to default it to 2. If we ever create a branching wizard it would make sense to default the number of paths to 2 in the wizard.
