### ISSUE TITLE
AT: show advanced authoring button for component at the top

### ISSUE THREAD

**Issue by hirokiterashima** [WISE-Community/WISE#925]
What you see now:
Advanced authoring button for the component is shown at the bottom of the component authoring.

What it should be instead:
Advanced authoring button for the component is shown at the top of the component authoring next to component title.

Justification:
This will make the UI more consistent and easier to use for advanced authors because they won't need to scroll down to find the button.

**Comment by geoffreykwan** [comment]
Completed https://github.com/WISE-Community/WISE/commit/aa37728c331d459189e83ad14d21f8c901dbfcac
