### ISSUE TITLE
severe warnings in tomcat log on shutdown tomcat 6.0.29

### ISSUE THREAD

**Issue by geoffreykwan** [WISE-Community/WISE#95]
when stopping tomcat 6.0.29, one wise4 server administrator noticed this output in the tomcat log:

INFO: Stopping service Catalina
Dec 1, 2010 2:34:27 PM org.apache.catalina.loader.WebappClassLoader clearThreadLocalMap
SEVERE: The web application [/jnlp] created a ThreadLocal with key of type [null] (value [com.kenai.jaffl.provider.StringIO$1@db766c1]) and a value of type [java.lang.ref.SoftReference] (value [java.lang.ref.SoftReference@3bb0ff0]) but failed to remove it when the web application was stopped. This is very likely to create a memory leak.
Dec 1, 2010 2:34:27 PM org.apache.catalina.loader.WebappClassLoader clearThreadLocalMap
SEVERE: The web application [/jnlp] created a ThreadLocal with key of type [null] (value [org.joni.StackMachine$1@6e135779]) and a value of type [java.lang.ref.WeakReference] (value [java.lang.ref.WeakReference@37d40164]) but failed to remove it when the web application was stopped. This is very likely to create a memory leak.
Dec 1, 2010 2:34:28 PM org.apache.catalina.loader.WebappClassLoader clearReferencesThreads
SEVERE: The web application [/host-manager] appears to have started a thread named [Poller SunPKCS11-Darwin] but has failed to stop it. This is very likely to create a memory leak.
Dec 1, 2010 2:34:29 PM org.apache.catalina.loader.WebappClassLoader clearReferencesJdbc
SEVERE: The web application [/webapp] registered the JBDC driver [org.apache.derby.jdbc.AutoloadedDriver] but failed to unregister it when the web application was stopped. To prevent a memory leak, the JDBC Driver has been forcibly unregistered.
Dec 1, 2010 2:34:29 PM org.apache.catalina.loader.WebappClassLoader clearReferencesJdbc
SEVERE: The web application [/webapp] registered the JBDC driver [org.h2.Driver] but failed to unregister it when the web application was stopped. To prevent a memory leak, the JDBC Driver has been forcibly unregistered.
Dec 1, 2010 2:34:29 PM org.apache.catalina.loader.WebappClassLoader clearReferencesJdbc
SEVERE: The web application [/webapp] registered the JBDC driver [com.mysql.jdbc.Driver] but failed to unregister it when the web application was stopped. To prevent a memory leak, the JDBC Driver has been forcibly unregistered.
Dec 1, 2010 2:34:29 PM org.apache.catalina.loader.WebappClassLoader clearReferencesThreads
SEVERE: The web application [/webapp] appears to have started a thread named [MySQL Statement Cancellation Timer] but has failed to stop it. This is very likely to create a memory leak.

does not seem critical.

Google Code Info:
Issue #: 94
Author: honchikun
Created On: 2010-12-01T23:46:14.000Z
Closed On:

**Comment by hirokiterashima** [comment]
We don't see this behavior anymore since a while ago, when we moved to tomcat 7 and 8 and WISE4.8
