### ISSUE TITLE
Max score display for students doesn't update on branch path assignment

### ISSUE THREAD

**Issue by breity** [WISE-Community/WISE#950]
In preview mode and for students: If a student gets assigned to a branch path that includes steps that have components with max scores, the total max score (displayed in the account menu in the upper right) for the project doesn't change.

Example project that shows the bug: [maxScoreBugTestProject.zip](https://github.com/WISE-Community/WISE/files/1389217/maxScoreBugTestProject.zip)

**Comment by hirokiterashima** [comment]
Will keep this in mind when we rewrite the tool in Angular.
