### ISSUE TITLE
Change TeacherDataService.getComponentStatesByWorkgroupIdAndComponentId() to require nodeId

### ISSUE THREAD

**Issue by geoffreykwan** [WISE-Community/WISE#973]
### Description

getComponentStatesByWorkgroupIdAndComponentId() function only takes in workgroupId and componentId right now. It should also take in nodeId just in case there are duplicate componentIds in the project.

**Comment by hirokiterashima** [comment]
Will keep this in mind when we rewrite the tool in Angular.
